export const mockUsers = [
  {
    id: "1",
    name: "John Doe",
    email: "john@university.edu",
    avatar: "/placeholder.svg?height=40&width=40",
    bio: "Computer Science student, love helping with tech stuff and design projects",
    campus: "University of Lagos",
    verified: true,
    rating: 4.8,
    gigsCompleted: 23,
    gigsPosted: 12,
    totalEarned: 45000,
    joinDate: "Jan 2024",
  },
  {
    id: "2",
    name: "Sarah Johnson",
    email: "sarah@university.edu",
    avatar: "/placeholder.svg?height=40&width=40",
    bio: "Business student offering tutoring and admin services",
    campus: "University of Lagos",
    verified: true,
    rating: 4.9,
    gigsCompleted: 31,
    gigsPosted: 8,
    totalEarned: 62000,
    joinDate: "Dec 2023",
  },
  {
    id: "3",
    name: "Mike Chen",
    email: "mike@university.edu",
    avatar: "/placeholder.svg?height=40&width=40",
    bio: "Engineering student, good with repairs and tech support",
    campus: "University of Lagos",
    verified: false,
    rating: 4.6,
    gigsCompleted: 18,
    gigsPosted: 15,
    totalEarned: 38000,
    joinDate: "Feb 2024",
  },
  {
    id: "4",
    name: "Emma Wilson",
    email: "emma@university.edu",
    avatar: "/placeholder.svg?height=40&width=40",
    bio: "Art student specializing in graphic design and creative projects",
    campus: "University of Lagos",
    verified: true,
    rating: 4.7,
    gigsCompleted: 27,
    gigsPosted: 6,
    totalEarned: 54000,
    joinDate: "Nov 2023",
  },
  {
    id: "5",
    name: "Alex Brown",
    email: "alex@university.edu",
    avatar: "/placeholder.svg?height=40&width=40",
    bio: "Math major offering tutoring in mathematics and statistics",
    campus: "University of Lagos",
    verified: true,
    rating: 4.9,
    gigsCompleted: 35,
    gigsPosted: 4,
    totalEarned: 71000,
    joinDate: "Oct 2023",
  },
  {
    id: "6",
    name: "Lisa Garcia",
    email: "lisa@university.edu",
    avatar: "/placeholder.svg?height=40&width=40",
    bio: "Language student offering translation and writing services",
    campus: "University of Lagos",
    verified: false,
    rating: 4.5,
    gigsCompleted: 14,
    gigsPosted: 9,
    totalEarned: 28000,
    joinDate: "Mar 2024",
  },
]

export const mockGigs = [
  {
    id: "1",
    title: "Do my laundry this weekend",
    description: "Need someone to wash, dry and fold my clothes. I have about 2 loads of laundry. Detergent provided.",
    category: "Laundry",
    type: "Manual",
    budget: 1500,
    budgetType: "fixed",
    location: "Hostel A",
    timeNeeded: "This Weekend",
    priority: "Normal",
    status: "Pending",
    posterId: "2",
    acceptedBy: null,
    postedDate: "2024-01-15",
    applications: 3,
  },
  {
    id: "2",
    title: "Design a flyer for my event",
    description:
      "Need a creative flyer design for a campus event. Should include event details, date, time, and be visually appealing.",
    category: "Design",
    type: "Digital",
    budget: 3000,
    budgetType: "negotiable",
    location: "Online",
    timeNeeded: "Tomorrow",
    priority: "Urgent",
    status: "Accepted",
    posterId: "3",
    acceptedBy: "1",
    postedDate: "2024-01-14",
    applications: 7,
  },
  {
    id: "3",
    title: "Buy food from cafeteria",
    description:
      "I'm sick and can't leave my room. Need someone to buy rice and chicken from the main cafeteria and deliver to Hostel B.",
    category: "Delivery",
    type: "Manual",
    budget: 800,
    budgetType: "fixed",
    location: "Main Cafeteria → Hostel B",
    timeNeeded: "ASAP",
    priority: "Urgent",
    status: "In Progress",
    posterId: "4",
    acceptedBy: "2",
    postedDate: "2024-01-15",
    applications: 5,
  },
  {
    id: "4",
    title: "Help with calculus homework",
    description:
      "Struggling with integration problems. Need someone to explain the concepts and help solve 10 problems.",
    category: "Tutoring",
    type: "Digital",
    budget: 2500,
    budgetType: "fixed",
    location: "Library Study Room",
    timeNeeded: "Today",
    priority: "Normal",
    status: "Completed",
    posterId: "5",
    acceptedBy: "1",
    postedDate: "2024-01-13",
    applications: 4,
  },
  {
    id: "5",
    title: "Fix my laptop screen",
    description:
      "Laptop screen is flickering and sometimes goes black. Need someone with tech skills to diagnose and fix if possible.",
    category: "Tech Help",
    type: "Manual",
    budget: 5000,
    budgetType: "negotiable",
    location: "Hostel C",
    timeNeeded: "This Week",
    priority: "Normal",
    status: "Pending",
    posterId: "6",
    acceptedBy: null,
    postedDate: "2024-01-15",
    applications: 2,
  },
]
